### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by radudang** [joticajulian/custom-feed#1]
Like we talked on Discord I made that concept for you.I hope you will like it.
![logo](https://user-images.githubusercontent.com/36233576/38028177-c2e04498-329a-11e8-8cf4-4216ee542abe.png)
![logowide](https://user-images.githubusercontent.com/36233576/38028180-c6a1237c-329a-11e8-8eba-78ab49ef79e6.png)

You can find all the files here: https://drive.google.com/open?id=1wuDUUzSKLQ6STk5-IGvWaLiEbnqtNz7w

**Comment by joticajulian** [comment]
Hi @radudang thank you very much. I like it

**Comment by radudang** [comment]
I am glad to hear that!

**Comment by joticajulian** [comment]
merged:
https://github.com/joticajulian/custom-feed/commit/6de31051e952b49b9c033752e20211114c8ba1e4
